add elasticsearch supervisor service
add elasticsearch supervisor service

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -3,11 +3,87 @@
 FROM python:2.7.15
 
 RUN apt-get update && apt-get install -y wget build-essential curl nginx supervisor
+RUN apt-get install -y software-properties-common
+
+
+# Java installation for elasticsearch
+RUN \
+  echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
+  add-apt-repository -y ppa:webupd8team/java && \
+  apt-get update && \
+  apt-get install -y --allow-unauthenticated oracle-java8-installer && \
+  rm -rf /var/lib/apt/lists/* && \
+  rm -rf /var/cache/oracle-jdk8-installer
+
+# Define commonly used JAVA_HOME variable
+ENV JAVA_HOME /usr/lib/jvm/java-8-oracle
+
+# install ES
+
+# grab gosu for easy step-down from root
+
+ENV GOSU_VERSION 1.10
+RUN set -x \
+	&& wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture)" \
+	&& wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture).asc" \
+	&& export GNUPGHOME="$(mktemp -d)" \
+	&& gpg --keyserver keyserver.ubuntu.com --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 \
+	&& gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu \
+	&& rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc \
+	&& chmod +x /usr/local/bin/gosu \
+	&& gosu nobody true
+
+RUN set -ex; \
+# https://artifacts.elastic.co/GPG-KEY-elasticsearch
+	key='46095ACC8548582C1A2699A9D27D666CD88E42B4'; \
+	export GNUPGHOME="$(mktemp -d)"; \
+	gpg --keyserver keyserver.ubuntu.com --recv-keys "$key"; \
+	gpg --export "$key" > /etc/apt/trusted.gpg.d/elastic.gpg; \
+	rm -rf "$GNUPGHOME"; \
+	apt-key list
+
+# https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-repositories.html
+# https://www.elastic.co/guide/en/elasticsearch/reference/5.0/deb.html
+RUN set -x \
+	&& apt-get update && apt-get install -y --no-install-recommends apt-transport-https && rm -rf /var/lib/apt/lists/* \
+	&& echo 'deb https://artifacts.elastic.co/packages/5.x/apt stable main' > /etc/apt/sources.list.d/elasticsearch.list
+
+ENV ELASTICSEARCH_VERSION 5.6.12
+ENV ELASTICSEARCH_DEB_VERSION 5.6.12
+
+RUN set -x \
+	\
+# don't allow the package to install its sysctl file (causes the install to fail)
+# Failed to write '262144' to '/proc/sys/vm/max_map_count': Read-only file system
+	&& dpkg-divert --rename /usr/lib/sysctl.d/elasticsearch.conf \
+	\
+	&& apt-get update \
+	&& apt-get install -y --no-install-recommends "elasticsearch=$ELASTICSEARCH_DEB_VERSION" \
+	&& rm -rf /var/lib/apt/lists/*
+
+ENV PATH /usr/share/elasticsearch/bin:$PATH
+
+WORKDIR /usr/share/elasticsearch
+
+RUN set -ex \
+	&& for path in \
+		./data \
+		./logs \
+		./config \
+		./config/scripts \
+	; do \
+		mkdir -p "$path"; \
+		chown -R elasticsearch:elasticsearch "$path"; \
+	done
+
+COPY log4j2.properties ./config
+
+EXPOSE 9200 9300
 
 WORKDIR /app
 
 
-COPY docker/install.sh initial_setup.py /app/
+COPY docker/install.sh /app/
 COPY docker/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
 
 RUN mkdir -p ~/model_lib && \
@@ -21,6 +97,9 @@ COPY requirements.txt /app/requirements.txt
 
 RUN pip install --no-cache-dir -r /app/requirements.txt
 
+COPY initial_setup.py /app/initial_setup.py
+RUN python /app/initial_setup.py
+
 # From start_server.sh
 
 ENV NAME="chatbot_ner"
@@ -31,6 +110,25 @@ ENV PORT=8081
 ENV TIMEOUT=600
 ENV DEBIAN_FRONTEND=noninteractive
 
+# Setting env variables
+# ENV vars defined in Dockerfile can be overwritten here before docker-compose up
+ENV NUM_WORKERS=1
+ENV MAX_REQUESTS=1000
+ENV DJANGO_WSGI_MODULE=chatbot_ner/wsgi.py
+ENV DJANGO_LOG_LEVEL=debug
+ENV DJANGO_DEBUG=False
+ENV ENGINE=elasticsearch
+
+# ES_HOST is host for ES that comes up with compose
+ENV ES_HOST=localhost
+ENV ES_PORT=9200
+ENV ES_INDEX_NAME=entity_data
+ENV ES_DOC_TYPE=data_dictionary
+ENV ES_BULK_MSG_SIZE=10000
+ENV ES_SEARCH_SIZE=10
+ENV CITY_MODEL_TYPE=crf
+ENV CITY_MODEL_PATH=
+ENV GOOGLE_TRANSLATE_API_KEY=
 
 #ENV DATE_MODEL_TYPE=crf
 #ENV DATE_MODEL_PATH=/root/models/models_live/date/crf/model.crf
